# $OpenBSD: Makefile.bsd-wrapper,v 1.5 2026/05/25 06:44:24 matthieu Exp $

SHARED_LIBS += va-drm 2.23
SHARED_LIBS += va-x11 2.23
SHARED_LIBS += va 2.23

LOCALBASE ?= /usr/local

CONFIGURE_ARGS= --disable-wayland --disable-glx
CONFIGURE_ARGS+= \
	--with-drivers-path=${DESTDIR}${X11BASE}/lib/modules/dri:${LOCALBASE}/lib/dri

.include <bsd.xorg.mk>
